### ISSUE TITLE
runscanner config

### ISSUE THREAD

**Issue by mijgmak** [TGAC/miso-lims#1137]
Hi, there are no information in miso admin documentation, how to configure runscanner since notification scanner is missing in latest release v.0.2.88.
Best,
Michael

**Comment by djcooke** [comment]
Run Scanner has fully replaced the old Notification Server. Please see the [runscanner module readme](https://github.com/TGAC/miso-lims/tree/develop/runscanner) for setup instructions. PacBio is supported with the runscanner module alone, but the additional [runscanner-illumina](https://github.com/TGAC/miso-lims/tree/develop/runscanner-illumina) module is required for Illumina support. Its setup is detailed in its own readme.

**Comment by mijgmak** [comment]
When I run Run Scanner in a separate tomcat instance I get the following error:
ERROR   2017-09-21 10:18:09,208 [ForkJoinPool-1-worker-5] uk.ac.bbsrc.tgac.miso.runscanner.Scheduler  - Failed to process run: /data/runs/analyzed/160519_SN7001299_0213_AHJVLWBCXX
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.lang.UNIXProcess$ProcessPipeInputStream@52a6e22a; line: 1, column: 0]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
        at uk.ac.bbsrc.tgac.miso.runscanner.processors.DefaultIllumina.process(DefaultIllumina.java:85)
        at uk.ac.bbsrc.tgac.miso.runscanner.Scheduler.lambda$queueDirectory$4(Scheduler.java:320)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by djcooke** [comment]
Have you set up [runscanner-illumina](https://github.com/TGAC/miso-lims/tree/develop/runscanner-illumina)?

**Comment by mijgmak** [comment]
Solved, error message because of empty folder. Could you please update readme and manuals regarding replaced Notification Server.
Best,
Michael

**Comment by djcooke** [comment]
Updated documentation in #1149
