### ISSUE TITLE
Update 0.2.115 - ERROR: Failed to save run: $RUN_ID

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1412]
I have updated to `0.2.115` last Friday without any issues and coming back to office I got some errors in MISO `miso_debug.log` (which I just noticed because some runs do not show up in MISO).

1. `runscanner-illumina` reported errors like:
```
ERROR   2018-04-23 10:25:17,468 [ForkJoinPool-1-worker-2] uk.ac.bbsrc.tgac.miso.runscanner.Scheduler  - Failed to process run: /project/solexadata/machine/SN106/180420_SN106_0262_A_CCAE7ANXX
java.lang.IllegalStateException: java.io.FileNotFoundException: /scratch/local2/de/miso-runscanner/tomcat/webapps/runscanner/WEB-INF/lib/spring-aop-4.3.6.RELEASE.jar (Too many open files)
```
I thought I could fix this by increasing `ulimit -n` (strange enough) ...
After increasing ulimits this error did not show up again ..

2. MISO still does not show some runs. `miso_debug.log` states:
```
2018-04-23 11:02:03 ERROR: Failed to save run: 180420_SN106_0262_A_CCAE7ANXX
uk.ac.bbsrc.tgac.miso.service.security.AuthorizationException: Current user does not have permission to modify this resource
    at uk.ac.bbsrc.tgac.miso.service.security.DefaultAuthorizationManager.throwIfNotWritable(DefaultAuthorizationManager.java:138)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultContainerService.create(DefaultContainerService.java:94)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultContainerService$$FastClassBySpringCGLIB$$d3adecdb.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultContainerService$$EnhancerBySpringCGLIB$$8b18f4e3.create(<generated>)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultRunService.updateContainerFromNotification(DefaultRunService.java:692)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultRunService.processNotification(DefaultRunService.java:558)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultRunService$$FastClassBySpringCGLIB$$a883b8d1.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
    at uk.ac.bbsrc.tgac.miso.service.impl.DefaultRunService$$EnhancerBySpringCGLIB$$63868285.processNotification(<generated>)
    at uk.ac.bbsrc.tgac.miso.webapp.service.RunScannerClient.processResults(RunScannerClient.java:92)
    at uk.ac.bbsrc.tgac.miso.webapp.service.RunScannerClient.scheduler(RunScannerClient.java:125)
    at sun.reflect.GeneratedMethodAccessor229.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

I haven't changed the config in no way, so I am a bit confused concerning the error message `AuthorizationException: Current user does not have permission to modify this resource`.

Any idea what happens here?
We now have just created some sequencing containers without having the actual runs in MISO; but MISO should find the container once the run is registered in MISO ...

**Comment by djcooke** [comment]
All runs and containers created via RunScanner should be owned by the 'notification' user, which is the same user it'll be checking authorization for. Is it possible that you made that user inactive, or otherwise modified that user recently?

**Comment by sklages** [comment]
Oops, that's a bit embarrassing, but somehow I managed to inactivate the `notification` user while updating our user page .. :confused: Thanks, "problem" solved.
